# Generated by Django 3.1.5 on 2021-01-10 10:43

from django.db import migrations, models
import django.db.models.deletion
import starapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0002_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='name',
        ),
        migrations.AlterField(
            model_name='face',
            name='face_Img',
            field=models.ImageField(),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge', to='starapp.face')),
                ('star_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star', to='starapp.face')),
                ('your_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your', to='starapp.face')),
            ],
        ),
    ]
