# Generated by Django 3.1.5 on 2021-01-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0003_auto_20210110_1143'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Save',
        ),
    ]
