# Generated by Django 3.1.5 on 2021-01-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starapp', '0004_auto_20210110_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='merge_face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merge', to='starapp.face'),
        ),
        migrations.AlterField(
            model_name='save',
            name='star_face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star', to='starapp.face'),
        ),
        migrations.AlterField(
            model_name='save',
            name='your_face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='your', to='starapp.face'),
        ),
    ]
